language: go
go: 1.9

install:
  - go get github.com/magefile/mage
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo

script:
  - mage vendor
  - mage install
  - hugo version

before_install:
  - export GOPATH=$HOME/go
  - export PATH=$PATH:$GOPATH/bin
  - echo $GOPATH
