language: go
go: 1.9
env:
  global:
    - HUGO_SOURCE_NAME="hugo_0.51_Linux-64bit"
    - HUGO_VERSION="v0.51"

before_install:
  - mkdir -p $HOME/bin
  - export PATH=$PATH:$HOME/bin

install:
  - cd $HOME/bin
  - curl -OL https://github.com/gohugoio/hugo/releases/download/$HUGO_VERSION/$HUGO_SOURCE_NAME.tar.gz
  - ls -al
  - tar xvzf $HUGO_SOURCE_NAME.tar.gz
  - cp $HUGO_SOURCE_NAME/hugo $HOME/bin

script:
  - hugo version
