language: go
go: 1.9
env:
  global:
    - HUGO_SOURCE_NAME="hugo_0.51_Linux-64bit"
    - HUGO_VERSION="v0.51"
before_install:
  - mkdir -p $HOME/bin
  - export PATH=$PATH:$HOME/bin
  - |
      (cd $HOME/bin 
      && curl -OL https://github.com/gohugoio/hugo/releases/download/$HUGO_VERSION/$HUGO_SOURCE_NAME.tar.gz
      && tar xvzf $HUGO_SOURCE_NAME.tar.gz)

install:
  - openssl aes-256-cbc -K $encrypted_824bf77d8762_key -iv $encrypted_824bf77d8762_iv
      -in gae_metapx.json.enc -out gae_metapx.json -d
script:
  - hugo version

deploy:
  provider: gae
  keyfile: gae_metapx.json
  project: <metapx-222113>
  skip_cleanup: true
