language: go
go: 1.9
env:
  HUGO_SOURCE_NAME="hugo_0.51_Linux-64bit"
  HUGO_VERSION="v0.51"

before_install:
  - mkdir -p $HOME/bin
  - export PATH=$PATH:$HOME/bin


install:
  - wget https://github.com/gohugoio/hugo/releases/download/$HUGO_VERSION/$HUGO_SOURCE_NAME.tar.gz $HOME/bin
  - cd $HOME/bin
  - tar xzf $HUGO_SOURCE_NAME.tar.gz
  - cp $HUGO_SOURCE_NAME/hugo $HOME/bin

script:
  - hugo version
